### ISSUE TITLE
 Result counter overflow

### ISSUE THREAD

**Issue by ATromp1** [a1tus/django-admin-cursor-paginator#10]
I'm getting the following bug when applying the cursor paginator to one of my models:
![image](https://github.com/a1tus/django-admin-cursor-paginator/assets/32782666/abbf555a-42c8-4e3f-9b03-98563fdba620)
It's clearly the overflow integer value but I can't seem to get rid of it.
Any thoughts?

**Comment by ATromp1** [comment]
I am using a custom change_list.html but my pagination block is defined in that file:
```
{% extends 'admin/change_list.html' %}
{% load i18n admin_urls %}
{% load admin_cursor_paginator_tags %}

{% block object-tools-items %}
  ...
  {{ block.super }}
{% endblock %}

{% block pagination %}{% admin_cursor_pagination cl %}{% endblock %}
```

**Comment by a1tus** [comment]
Django passes this context to search form:
```
def search_form(cl):
    """
    Display a search form for searching the list.
    """
    return {
        "cl": cl,
        "show_result_count": cl.result_count != cl.full_result_count,
        "search_var": SEARCH_VAR,
        "is_popup_var": IS_POPUP_VAR,
        "is_facets_var": IS_FACETS_VAR,
    }
```

And this app fixes this behaviour by default like this (so `show_result_count` must be False):
```
def get_results(self, *args, **kwargs):
        super().get_results(*args, **kwargs)
        if self.query and self.model_admin.show_query_result_count:
            self.result_count = self.queryset.count()
        else:
            # small hack to prevent full count (which is unknown) from being shown in `search_form.html`
            self.full_result_count = self.result_count
```

So I suppose (as you are using custom list templates), you are also using some other admin customizations that break this.
