### ISSUE TITLE
Python >=3.7 not >=3.4

### ISSUE THREAD

**Issue by artoonie** [a1tus/django-admin-cursor-paginator#2]
Hi, 
On PyPi, this package is listed as compatible with python >=3.4, however it uses `fromisoformat` which is introduced in 3.7 I believe: https://stackoverflow.com/questions/60266554/type-object-datetime-datetime-has-no-attribute-fromisoformat

Can you update PyPi to reflect this?

**Comment by a1tus** [comment]
Hi, good catch, thank you. I decided that it would be better just to fix it :)

So version 0.1.1 is released here and on PyPI.
